version: '3' 
services:    
  db:        
    image: mysql:5.6 
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker 
      MYSQL_PASSWORD: docker
    container_name: mydb
    ports: 
      - "3306:3306"
    tty: true
    volumes:
      - ./mysql/db_data:/var/lib/mysql
  web:
    container_name: myserver
    build:
      context: ./phpapache
    volumes:
      - ./certificates:/etc/apache2/ssl_keys
      - ./phpapache/html:/var/www/html
    tty: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db    